spring:
    datasource:
        name: source
        url: jdbc:mysql://localhost:3306/springboot?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
        username: root
        password: asd20021003
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
    mvc:
      view:
            prefix: /  
            suffix: .jsp

      servlet:
        load-on-startup: 100
        # 配置日志输出的级别,输出格式%p%m%n 级别 内容 换行
logging:
    level:
        root: debug
        com.tmf.bss.dao: debug
mybatis:
  mapperLocations: classpath*:mappers/*.xml
  typeAliasesPackage: com.tmf.bbs
server:
  port: 8086

